version: '2'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
#    environment:
#        - cluster.name=docker-cluster
#        - discovery.type=single-node
    environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
        memlock:
          soft: -1
          hard: -1
    ports:
        - "9200:9200"
    volumes:
        - ./docker/elastic/data:/usr/share/elasticsearch/data
  elastictest:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
#    environment:
#        - cluster.name=docker-cluster
#        - discovery.type=single-node
    environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - "discovery.zen.ping.unicast.hosts=elastic"
    ulimits:
        memlock:
          soft: -1
          hard: -1
    volumes:
        - ./docker/elastictest/data:/usr/share/elasticsearch/data
  chrome:
    image: selenium/standalone-chrome:3.141.59-dubnium
    ports:
        - "4444:4444"
  db:
    image: mysql:5.7 # TODO No idea why 8.0.13 SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
        - ./docker/mysql/data/:/var/lib/mysql/
        - ./docker/mysql/entrypoint/:/docker-entrypoint-initdb.d/
    ports:
        - '6306:3306'
  php:
    image: yiisoftware/yii-php:7.2-apache
    volumes:
        - ~/.composer-docker/cache:/root/.composer/cache:delegated
        - ./:/app:delegated
        - ./docker/apache2/sites-enabled/:/etc/apache2/sites-enabled/
    ports:
        - '8080:80'
